export const CART_ADD_ITEMS='CART_ADD_ITEMS'
export const CART_REMOVE_ITEMS='CART_REMOVE_ITEMS'
export const CART_SHIPPING_ADDRESS='CART_SHIPPING_ADDRESS'
export const CART_PAYMENT_METHOD='CART_PAYMENT_METHOD'