export const ORDER_REQUEST='ORDER_REQUEST'
export const ORDER_SUCCESS='ORDER_SUCCESS'
export const ORDER_FAILURE='ORDER_FAILURE'

export const ORDER_DETAIL_REQUEST='ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS='ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_FAILURE='ORDER_DETAIL_FAILURE'

//PAYMENT CONSTANTS
export const ORDER_PAY_REQUEST='ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS='ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAILURE='ORDER_PAY_FAILURE'
export const ORDER_PAY_RESET='ORDER_PAY_RESET'

export const MY_ORDER_REQUEST='MY_ORDER_REQUEST'
export const MY_ORDER_SUCCESS='MY_ORDER_SUCCESS'
export const MY_ORDER_FAILURE='MY_ORDER_FAILURE'
export const MY_ORDER_RESET='MY_ORDER_RESET'
