export const  PRODUCTS_FETCH='PRODUCTS_FETCH'
export const  PRODUCTS_SUCCESS='PRODUCTS_SUCCESS'
export const  PRODUCTS_FAILURE='PRODUCTS_FAILURE'

export const  PRODUCT_DETAILS_FETCH='PRODUCT_DETAILS_FETCH'
export const  PRODUCT_DETAILS_SUCCESS='PRODUCT_DETAILS_SUCCESS'
export const  PRODUCT_DETAILS_FAILURE='PRODUCT_DETAILS_FAILURE'
