export const USER_LOG_REQUEST= 'USER_LOG_REQUEST'
export const USER_LOG_SUCCESS= 'USER_LOG_SUCCESS'
export const USER_LOG_FAILURE= 'USER_LOG_FAILURE'
export const USER_LOG_LOGOUT= 'USER_LOG_LOGOUT'

export const USER_REG_REQUEST= 'USER_REG_REQUEST'
export const USER_REG_SUCCESS= 'USER_REG_SUCCESS'
export const USER_REG_FAILURE= 'USER_REG_FAILURE'

export const USER_PROFILE_REQUEST= 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS= 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAILURE= 'USER_PROFILE_FAILURE'

export const USER_UPDATE_REQUEST= 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS= 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAILURE= 'USER_UPDATE_FAILURE'
export const USER_UPDATE_RESET= 'USER_UPDATE_RESET'